---

apiVersion: v1
kind: ConfigMap
metadata:
  name: portal
  namespace: portal
data:
  # The log level. Possible values are: "debug", "info", "warn", "error".
  loglevel: "info"

  # Define the git repo that is used to build the portal site.
  src: "https://github.com/salt-labs/trash-can.git"

  # The caddy configuration file.
  caddyfile: |
    :80 {
      root /public
      file_server
      log {
        output file /var/log/caddy/access.log
      }
      errors {
        log {
          output file /var/log/caddy/error.log
        }
      }
    }
