---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portal-public
  namespace: portal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portal-workdir
  namespace: portal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
