---

apiVersion: v1
kind: Service
metadata:
  name: portal-service
  namespace: portal
spec:
  selector:
    app: portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
